apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: crd-vcluster
  namespace: loft-p-default
  labels:
    app.kubernetes.io/instance: keycloak-tenant
    loft.sh/import-argocd: 'true'
  annotations:
    loft.sh/preserve-namespace-on-deletion: 'true'
spec:
  displayName: crd-vcluster
  owner:
    user: admin
  templateRef:
    name: isolated-vcluster
  clusterRef:
    cluster: eu-cluster
    namespace: keycloak
    virtualCluster: crd-vcluster
  access:
    - name: instance-admin-access
      verbs:
        - create
        - use
        - get
        - update
        - delete
        - patch
      subresources:
        - logs
        - kubeconfig
      teams:
        - sales
